---
- name: Connection to my servers
  hosts: Linux1
  become: yes


  vars:
    - tomcat_version: tomcat-8.0.53
    - java_version: java-12.0.1-openjdk
    
  
  tasks:
  - name: Update and upgrade yum packages
    yum: name=* state=latest update_cache=yes

  - name: Install JDK
    yum: name=java-12-openjdk-devel state=present

  - name: JAVA-HOME set
    shell: "echo JAVA_HOME=/usr/java/jdk-12.0.1/bin/java >/etc/environment"

  - name: add group "tomcat"
    group: name=tomcat

  - name: add user "tomcat"
    user: name=tomcat group=tomcat home=/opt/tomcat/ createhome=no
    become: True
    become_method: sudo

  - name: Download Tomcat
    get_url:
      url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.53/bin/apache-tomcat-8.0.53.tar.gz
      dest: /opt/apache-tomcat-8.0.53.tar.gz

  - name: Create directory
    file:
      path=/opt/tomcat/{{ tomcat_version }}
      mode=0755
      owner=tomcat
      group=tomcat
      state=directory
  
  - name: Extract archive
    unarchive: 
      src: /opt/apache-tomcat-8.0.53.tar.gz
      dest: /opt/tomcat/{{ tomcat_version }}/
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Configure Tomcat service
    copy:
      src: tomcat.service
      dest: /etc/systemd/system/
      mode: 0755

  - name: Configure Tomcat users
    copy:
      src: tomcat-users.xml
      dest: /opt/tomcat/{{ tomcat_version }}/conf/
      mode: 0755

  - name: Configure Tomcat context
    copy:
      src: context.xml
      dest: /opt/tomcat/{{ tomcat_version }}/webapps/manager/META-INF/
      mode: 0755

  - name: set owner tomcat
    shell: chown -R tomcat:tomcat /opt/tomcat

  - name: Start service tomcat, if not started
    service:
      name: tomcat
      state: started

  - name: Java version 
    debug: 
      msg: "Java version: {{ java_version }}" 

  - name: Tomcat version 
    debug: 
      msg: "Tomcat version: {{ tomcat_version }}"
  
  - name: Availability check (with curl) to Tomcat
    shell: curl -I http://192.168.145.159:8080 | grep HTTP  
    register: res1

  - name: Availability check (systemd) to Tomcat
    shell: systemctl status tomcat | grep active
    register: res2
  
  - name: Availability (check port) Tomcat
    shell: netstat -tlnp | grep ":8080"
    register: res3

  - name: Checking user "student" exists
    shell: cat /opt/tomcat/{{ tomcat_version }}/conf/tomcat-users.xml | grep "username"
    register: res4 

  - name: Check service Tomcat with curl
    debug: var=res1

  - name: Check service Tomcat with systemd
    debug: var=res2

  - name: Check service port Tomcat
    debug: var=res3
 
  - name: Checking user 
    debug: var=res4

  
